parameters:
  - name: dockerImage
    type: string
    default: 'testexec'
  - name: dockerTag
    type: string
    default: '1'

variables:
  - group: 'Secrets'

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DockerRun
    displayName: 'Install Docker and Run Container'
    jobs:
      - job: DockerJob
        steps:
          - script: |
              echo "Running in Docker"
              echo ${{ variables.docker_password }} | docker login --username ${{ variables.docker_user }} --password-stdin
              docker run -d -p 3000:3000 ${{ variables.docker_user }}/${{ parameters.dockerImage }}:${{ parameters.dockerTag }}
            displayName: 'Running Docker Container'