parameters:
  - name: repoUrl
    type: string
    default: 'https://github.com/QoT-Solutions/safeSpeed_BackEnd.git'
  - name: dockerUser
    type: string
    default: 'kopanomgn'
  - name: dockerPass
    type: string
    default: 'KopanoMagano@97'
  - name: dockerImage
    type: string
    default: 'testexec'
  - name: dockerTag
    type: string
    default: '1'

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DockerRun
    displayName: 'Install Docker and Run Container'
    jobs:
      - job: DockerJob
        steps:
          - script: |
              echo "Running in Docker"
              docker login --username ${{ parameters.dockerUser }} --password ${{ parameters.dockerPass }}
              docker run -d -p 3000:3000 ${{ parameters.dockerUser }}/${{ parameters.dockerImage }}:${{ parameters.dockerTag }}
            displayName: 'Running Docker Container'